apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginxingress-nginx-ingress-configmap
subjects:
- kind: ServiceAccount
  name: nginx-ingress
  namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: nginxingress-nginx-ingress-configmap
  apiGroup: rbac.authorization.k8s.io