apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxingress-configmap
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["nginxingress-nginx-ingress"]
